
# A sample of about 50 different benchmark runs, not noisy, run quickly enough,
# that appear to be somewhat diverse.

[[Benchmarks]]
  Name = "wazero"
  Benchmarks = "BenchmarkInvocation/interpreter/(string_manipulation_size_50|fib_for_20|random_mat_mul_size_20)|BenchmarkCompilation/with"

[[Benchmarks]]
  Name = "toml"
  Benchmarks = "BenchmarkDecode/large-doc"

[[Benchmarks]]
  Name = "minio"
  Tests = "none" # Don't run these tests; they hang, etc.
  Benchmarks = "Benchmark(MarshalMsgdataUsageCacheInfo|DecodehealingTracker|DataUpdateTracker|AppendMsgResyncTargetsInfo)"
  GcEnv = ["GO111MODULE=on"]

[[Benchmarks]]
  Name = "hugo_hugolib"
  Benchmarks = "Benchmark(ResourceChainPostProcess|ReplaceShortcodeTokens|MergeByLanguage|(Cascade/langs-1-8))"

[[Benchmarks]]
  Name = "ethereum_core"
  Benchmarks = "BenchmarkP.*10000"

[[Benchmarks]]
  Name = "shopify_sarama"
  Benchmarks = "BenchmarkBroker" # BenchmarkStick.* are noisy

[[Benchmarks]]
  Name = "aws_restjson"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "aws_restxml"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "aws_jsonrpc"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "aws_jsonutil"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "ethereum_bitutil"
  Benchmarks = "Benchmark(BaseTest2KB|FastTest2KB|Encoding4KBVerySparse)"

[[Benchmarks]]
  Name = "ethereum_ethash"
  Benchmarks = "BenchmarkHashimotoLight"

[[Benchmarks]]
  Name = "ethereum_sha3"
  Benchmarks = "BenchmarkSha3_224_MTU"

[[Benchmarks]]
  Name = "ethereum_ecies"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "ethereum_corevm"
  Benchmarks = "BenchmarkOpDiv128"

[[Benchmarks]]
  Name = "ethereum_trie"
  Benchmarks = "Benchmark[HCKGU].*/10K" # Prove and VerifyProof are noisy

[[Benchmarks]]
  Name = "spexs2"
  Benchmarks = "BenchmarkRun/10k/1"

[[Benchmarks]]
  Name = "gonum_blas_native"
  Benchmarks = "Benchmark(DasumMediumUnitaryInc|Dnrm2MediumPosInc)" # not all benchmarks

[[Benchmarks]]
  Name = "gonum_lapack_native"
  Benchmarks = "BenchmarkDgeev/Circulant10"

[[Benchmarks]]
  Name = "gonum_mat"
  Benchmarks = "Benchmark(MulWorkspaceDense1000Hundredth|ScaleVec10000Inc20)"

[[Benchmarks]]
  Name = "semver"
  Benchmarks = "BenchmarkValidateVersionTildeFail"

[[Benchmarks]]
  Name = "k8s_cache"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "k8s_workqueue"
  Benchmarks = "BenchmarkParallelizeUntil" # DelayingQueue is noisy

[[Benchmarks]]
  Name = "uuid"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "gonum_topo"
  Benchmarks = "Benchmark(TarjanSCCGnp_1000_half|TarjanSCCGnp_10_tenth)"

[[Benchmarks]]
  Name = "gonum_path"
  Benchmarks = "Benchmark(AStarUndirectedmallWorld_10_2_2_2_Heur|Dominators/nested_if_n256)"

[[Benchmarks]]
  Name = "gonum_community"
  Benchmarks = "BenchmarkLouvainDirectedMultiplex"

[[Benchmarks]]
  Name = "gonum_traverse"
  Benchmarks = "BenchmarkWalkAllBreadthFirstGnp_(10|1000)_tenth" # more difference by size than anything else

[[Benchmarks]]
  Name = "capnproto2"
  Benchmarks = "Benchmark(TextMovementBetweenSegments|Growth_MultiSegment)"

[[Benchmarks]]
  Name = "uber_zap"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "uber_tally"
  Benchmarks = "ScopeTaggedNoCachedSubscopes|HistogramAllocation"

[[Benchmarks]]
  Name = "bindata"
  Benchmarks = "Benchmark"

[[Benchmarks]]
  Name = "cespare_mph"
  Benchmarks = "BenchmarkBuild"

# Used by InfluxDB and Prometheus
[[Benchmarks]]
  Name = "cespare_xxhash"
  Benchmarks = "BenchmarkHashes/.*,direct,string,n=10MB"

[[Benchmarks]]
  Name = "gtank_blake2s"
  Benchmarks = "BenchmarkHash8K"

[[Benchmarks]]
  Name = "gtank_ed25519"
  Benchmarks = "Benchmark(IsOnCurve|ScalarMult)"

[[Benchmarks]]
  Name = "ajstarks_deck_generate"
  Benchmarks = "Benchmark(Polygon|Arc)"

[[Benchmarks]]
  Name = "benhoyt_goawk_1_18"
  Benchmarks = "BenchmarkR"

[[Benchmarks]]
  Name = "ericlagergren_decimal"
  Benchmarks = "BenchmarkPi/foo=.*/prec=100"

[[Benchmarks]]
  Name = "dustin_broadcast"
  Benchmarks = "Benchmark[^B]" #Brodcast is noisy

[[Benchmarks]]
  Name = "dustin_humanize"
  Benchmarks = "BenchmarkParseBigBytes"

[[Benchmarks]]
  Name = "bloom_bloom"
  Benchmarks = "Benchmark[SC]" # avoid "Estimated"

[[Benchmarks]]
  Name = "kanzi"
  Benchmarks = "Benchmark(FPAQ|LZ|MTFT)$"

[[Benchmarks]]
  Name = "commonmark_markdown"
  Benchmarks = "Benchmark(RenderSpec|RenderSpecBlackFriday2)"

